
import { axiosInstance } from '../../src/utils/http';

export const APIService = {
    async getTrendingRepos() {
        let date = new Date();
        date.setDate(date.getDate() - 7);
        const finalDate = date.getFullYear() + '-0' + (date.getMonth() + 1) + '-0' + date.getDate();
        console.log('finalDate', finalDate);
        return axiosInstance.get(`search/repositories?q=created:>${finalDate}&sort=stars&order=desc&per_page=4&page=1`)
    },

    async getCommits(repoName) {
        return axiosInstance.get(`repos/${repoName}/commits?q=sort:committer-date-desc&per_page=10&page=1`)
    },

    async getTrendingReposOffline() {
        return {
            "data": {
                "total_count": 648987,
                "incomplete_results": false,
                "items": [
                    {
                        "id": 367284699,
                        "node_id": "MDEwOlJlcG9zaXRvcnkzNjcyODQ2OTk=",
                        "name": "lima",
                        "full_name": "AkihiroSuda/lima",
                        "private": false,
                        "owner": {
                            "login": "AkihiroSuda",
                            "id": 9248427,
                            "node_id": "MDQ6VXNlcjkyNDg0Mjc=",
                            "avatar_url": "https://avatars.githubusercontent.com/u/9248427?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/AkihiroSuda",
                            "html_url": "https://github.com/AkihiroSuda",
                            "followers_url": "https://api.github.com/users/AkihiroSuda/followers",
                            "following_url": "https://api.github.com/users/AkihiroSuda/following{/other_user}",
                            "gists_url": "https://api.github.com/users/AkihiroSuda/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/AkihiroSuda/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/AkihiroSuda/subscriptions",
                            "organizations_url": "https://api.github.com/users/AkihiroSuda/orgs",
                            "repos_url": "https://api.github.com/users/AkihiroSuda/repos",
                            "events_url": "https://api.github.com/users/AkihiroSuda/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/AkihiroSuda/received_events",
                            "type": "User",
                            "site_admin": false
                        },
                        "html_url": "https://github.com/AkihiroSuda/lima",
                        "description": "Lima: Linux-on-Mac (\"macOS subsystem for Linux\", \"containerd for Mac\")",
                        "fork": false,
                        "url": "https://api.github.com/repos/AkihiroSuda/lima",
                        "forks_url": "https://api.github.com/repos/AkihiroSuda/lima/forks",
                        "keys_url": "https://api.github.com/repos/AkihiroSuda/lima/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/AkihiroSuda/lima/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/AkihiroSuda/lima/teams",
                        "hooks_url": "https://api.github.com/repos/AkihiroSuda/lima/hooks",
                        "issue_events_url": "https://api.github.com/repos/AkihiroSuda/lima/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/AkihiroSuda/lima/events",
                        "assignees_url": "https://api.github.com/repos/AkihiroSuda/lima/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/AkihiroSuda/lima/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/AkihiroSuda/lima/tags",
                        "blobs_url": "https://api.github.com/repos/AkihiroSuda/lima/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/AkihiroSuda/lima/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/AkihiroSuda/lima/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/AkihiroSuda/lima/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/AkihiroSuda/lima/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/AkihiroSuda/lima/languages",
                        "stargazers_url": "https://api.github.com/repos/AkihiroSuda/lima/stargazers",
                        "contributors_url": "https://api.github.com/repos/AkihiroSuda/lima/contributors",
                        "subscribers_url": "https://api.github.com/repos/AkihiroSuda/lima/subscribers",
                        "subscription_url": "https://api.github.com/repos/AkihiroSuda/lima/subscription",
                        "commits_url": "https://api.github.com/repos/AkihiroSuda/lima/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/AkihiroSuda/lima/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/AkihiroSuda/lima/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/AkihiroSuda/lima/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/AkihiroSuda/lima/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/AkihiroSuda/lima/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/AkihiroSuda/lima/merges",
                        "archive_url": "https://api.github.com/repos/AkihiroSuda/lima/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/AkihiroSuda/lima/downloads",
                        "issues_url": "https://api.github.com/repos/AkihiroSuda/lima/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/AkihiroSuda/lima/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/AkihiroSuda/lima/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/AkihiroSuda/lima/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/AkihiroSuda/lima/labels{/name}",
                        "releases_url": "https://api.github.com/repos/AkihiroSuda/lima/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/AkihiroSuda/lima/deployments",
                        "created_at": "2021-05-14T07:30:56Z",
                        "updated_at": "2021-05-16T13:58:16Z",
                        "pushed_at": "2021-05-16T12:19:00Z",
                        "git_url": "git://github.com/AkihiroSuda/lima.git",
                        "ssh_url": "git@github.com:AkihiroSuda/lima.git",
                        "clone_url": "https://github.com/AkihiroSuda/lima.git",
                        "svn_url": "https://github.com/AkihiroSuda/lima",
                        "homepage": "",
                        "size": 90,
                        "stargazers_count": 1048,
                        "watchers_count": 1048,
                        "language": "Go",
                        "has_issues": true,
                        "has_projects": true,
                        "has_downloads": true,
                        "has_wiki": false,
                        "has_pages": false,
                        "forks_count": 11,
                        "mirror_url": null,
                        "archived": false,
                        "disabled": false,
                        "open_issues_count": 7,
                        "license": {
                            "key": "apache-2.0",
                            "name": "Apache License 2.0",
                            "spdx_id": "Apache-2.0",
                            "url": "https://api.github.com/licenses/apache-2.0",
                            "node_id": "MDc6TGljZW5zZTI="
                        },
                        "forks": 11,
                        "open_issues": 7,
                        "watchers": 1048,
                        "default_branch": "master",
                        "score": 1
                    },
                    {
                        "id": 366715028,
                        "node_id": "MDEwOlJlcG9zaXRvcnkzNjY3MTUwMjg=",
                        "name": "send-my",
                        "full_name": "positive-security/send-my",
                        "private": false,
                        "owner": {
                            "login": "positive-security",
                            "id": 84080129,
                            "node_id": "MDEyOk9yZ2FuaXphdGlvbjg0MDgwMTI5",
                            "avatar_url": "https://avatars.githubusercontent.com/u/84080129?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/positive-security",
                            "html_url": "https://github.com/positive-security",
                            "followers_url": "https://api.github.com/users/positive-security/followers",
                            "following_url": "https://api.github.com/users/positive-security/following{/other_user}",
                            "gists_url": "https://api.github.com/users/positive-security/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/positive-security/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/positive-security/subscriptions",
                            "organizations_url": "https://api.github.com/users/positive-security/orgs",
                            "repos_url": "https://api.github.com/users/positive-security/repos",
                            "events_url": "https://api.github.com/users/positive-security/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/positive-security/received_events",
                            "type": "Organization",
                            "site_admin": false
                        },
                        "html_url": "https://github.com/positive-security/send-my",
                        "description": "Upload arbitrary data via Apple's Find My network.",
                        "fork": false,
                        "url": "https://api.github.com/repos/positive-security/send-my",
                        "forks_url": "https://api.github.com/repos/positive-security/send-my/forks",
                        "keys_url": "https://api.github.com/repos/positive-security/send-my/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/positive-security/send-my/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/positive-security/send-my/teams",
                        "hooks_url": "https://api.github.com/repos/positive-security/send-my/hooks",
                        "issue_events_url": "https://api.github.com/repos/positive-security/send-my/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/positive-security/send-my/events",
                        "assignees_url": "https://api.github.com/repos/positive-security/send-my/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/positive-security/send-my/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/positive-security/send-my/tags",
                        "blobs_url": "https://api.github.com/repos/positive-security/send-my/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/positive-security/send-my/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/positive-security/send-my/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/positive-security/send-my/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/positive-security/send-my/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/positive-security/send-my/languages",
                        "stargazers_url": "https://api.github.com/repos/positive-security/send-my/stargazers",
                        "contributors_url": "https://api.github.com/repos/positive-security/send-my/contributors",
                        "subscribers_url": "https://api.github.com/repos/positive-security/send-my/subscribers",
                        "subscription_url": "https://api.github.com/repos/positive-security/send-my/subscription",
                        "commits_url": "https://api.github.com/repos/positive-security/send-my/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/positive-security/send-my/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/positive-security/send-my/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/positive-security/send-my/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/positive-security/send-my/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/positive-security/send-my/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/positive-security/send-my/merges",
                        "archive_url": "https://api.github.com/repos/positive-security/send-my/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/positive-security/send-my/downloads",
                        "issues_url": "https://api.github.com/repos/positive-security/send-my/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/positive-security/send-my/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/positive-security/send-my/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/positive-security/send-my/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/positive-security/send-my/labels{/name}",
                        "releases_url": "https://api.github.com/repos/positive-security/send-my/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/positive-security/send-my/deployments",
                        "created_at": "2021-05-12T12:54:32Z",
                        "updated_at": "2021-05-16T13:58:36Z",
                        "pushed_at": "2021-05-12T18:12:05Z",
                        "git_url": "git://github.com/positive-security/send-my.git",
                        "ssh_url": "git@github.com:positive-security/send-my.git",
                        "clone_url": "https://github.com/positive-security/send-my.git",
                        "svn_url": "https://github.com/positive-security/send-my",
                        "homepage": "",
                        "size": 12377,
                        "stargazers_count": 923,
                        "watchers_count": 923,
                        "language": "C",
                        "has_issues": true,
                        "has_projects": true,
                        "has_downloads": true,
                        "has_wiki": true,
                        "has_pages": false,
                        "forks_count": 31,
                        "mirror_url": null,
                        "archived": false,
                        "disabled": false,
                        "open_issues_count": 2,
                        "license": {
                            "key": "agpl-3.0",
                            "name": "GNU Affero General Public License v3.0",
                            "spdx_id": "AGPL-3.0",
                            "url": "https://api.github.com/licenses/agpl-3.0",
                            "node_id": "MDc6TGljZW5zZTE="
                        },
                        "forks": 31,
                        "open_issues": 2,
                        "watchers": 923,
                        "default_branch": "main",
                        "score": 1
                    },
                    {
                        "id": 366097168,
                        "node_id": "MDEwOlJlcG9zaXRvcnkzNjYwOTcxNjg=",
                        "name": "PhotorealismEnhancement",
                        "full_name": "intel-isl/PhotorealismEnhancement",
                        "private": false,
                        "owner": {
                            "login": "intel-isl",
                            "id": 23507030,
                            "node_id": "MDEyOk9yZ2FuaXphdGlvbjIzNTA3MDMw",
                            "avatar_url": "https://avatars.githubusercontent.com/u/23507030?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/intel-isl",
                            "html_url": "https://github.com/intel-isl",
                            "followers_url": "https://api.github.com/users/intel-isl/followers",
                            "following_url": "https://api.github.com/users/intel-isl/following{/other_user}",
                            "gists_url": "https://api.github.com/users/intel-isl/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/intel-isl/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/intel-isl/subscriptions",
                            "organizations_url": "https://api.github.com/users/intel-isl/orgs",
                            "repos_url": "https://api.github.com/users/intel-isl/repos",
                            "events_url": "https://api.github.com/users/intel-isl/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/intel-isl/received_events",
                            "type": "Organization",
                            "site_admin": false
                        },
                        "html_url": "https://github.com/intel-isl/PhotorealismEnhancement",
                        "description": "Code & Data for Enhancing Photorealism Enhancement",
                        "fork": false,
                        "url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement",
                        "forks_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/forks",
                        "keys_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/teams",
                        "hooks_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/hooks",
                        "issue_events_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/events",
                        "assignees_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/tags",
                        "blobs_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/languages",
                        "stargazers_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/stargazers",
                        "contributors_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/contributors",
                        "subscribers_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/subscribers",
                        "subscription_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/subscription",
                        "commits_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/merges",
                        "archive_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/downloads",
                        "issues_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/labels{/name}",
                        "releases_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/intel-isl/PhotorealismEnhancement/deployments",
                        "created_at": "2021-05-10T15:51:41Z",
                        "updated_at": "2021-05-16T13:51:38Z",
                        "pushed_at": "2021-05-13T15:51:23Z",
                        "git_url": "git://github.com/intel-isl/PhotorealismEnhancement.git",
                        "ssh_url": "git@github.com:intel-isl/PhotorealismEnhancement.git",
                        "clone_url": "https://github.com/intel-isl/PhotorealismEnhancement.git",
                        "svn_url": "https://github.com/intel-isl/PhotorealismEnhancement",
                        "homepage": "",
                        "size": 16041,
                        "stargazers_count": 514,
                        "watchers_count": 514,
                        "language": "HTML",
                        "has_issues": true,
                        "has_projects": true,
                        "has_downloads": true,
                        "has_wiki": true,
                        "has_pages": true,
                        "forks_count": 14,
                        "mirror_url": null,
                        "archived": false,
                        "disabled": false,
                        "open_issues_count": 1,
                        "license": null,
                        "forks": 14,
                        "open_issues": 1,
                        "watchers": 514,
                        "default_branch": "main",
                        "score": 1
                    },
                    {
                        "id": 365987268,
                        "node_id": "MDEwOlJlcG9zaXRvcnkzNjU5ODcyNjg=",
                        "name": "mobile-app-automizer",
                        "full_name": "automizer/mobile-app-automizer",
                        "private": false,
                        "owner": {
                            "login": "automizer",
                            "id": 84228672,
                            "node_id": "MDEyOk9yZ2FuaXphdGlvbjg0MjI4Njcy",
                            "avatar_url": "https://avatars.githubusercontent.com/u/84228672?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/automizer",
                            "html_url": "https://github.com/automizer",
                            "followers_url": "https://api.github.com/users/automizer/followers",
                            "following_url": "https://api.github.com/users/automizer/following{/other_user}",
                            "gists_url": "https://api.github.com/users/automizer/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/automizer/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/automizer/subscriptions",
                            "organizations_url": "https://api.github.com/users/automizer/orgs",
                            "repos_url": "https://api.github.com/users/automizer/repos",
                            "events_url": "https://api.github.com/users/automizer/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/automizer/received_events",
                            "type": "Organization",
                            "site_admin": false
                        },
                        "html_url": "https://github.com/automizer/mobile-app-automizer",
                        "description": "You can automize iOS and Android app's build, upload and versioning processes via Mobile App Automizer CLI tool.",
                        "fork": false,
                        "url": "https://api.github.com/repos/automizer/mobile-app-automizer",
                        "forks_url": "https://api.github.com/repos/automizer/mobile-app-automizer/forks",
                        "keys_url": "https://api.github.com/repos/automizer/mobile-app-automizer/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/automizer/mobile-app-automizer/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/automizer/mobile-app-automizer/teams",
                        "hooks_url": "https://api.github.com/repos/automizer/mobile-app-automizer/hooks",
                        "issue_events_url": "https://api.github.com/repos/automizer/mobile-app-automizer/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/automizer/mobile-app-automizer/events",
                        "assignees_url": "https://api.github.com/repos/automizer/mobile-app-automizer/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/automizer/mobile-app-automizer/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/automizer/mobile-app-automizer/tags",
                        "blobs_url": "https://api.github.com/repos/automizer/mobile-app-automizer/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/automizer/mobile-app-automizer/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/automizer/mobile-app-automizer/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/automizer/mobile-app-automizer/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/automizer/mobile-app-automizer/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/automizer/mobile-app-automizer/languages",
                        "stargazers_url": "https://api.github.com/repos/automizer/mobile-app-automizer/stargazers",
                        "contributors_url": "https://api.github.com/repos/automizer/mobile-app-automizer/contributors",
                        "subscribers_url": "https://api.github.com/repos/automizer/mobile-app-automizer/subscribers",
                        "subscription_url": "https://api.github.com/repos/automizer/mobile-app-automizer/subscription",
                        "commits_url": "https://api.github.com/repos/automizer/mobile-app-automizer/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/automizer/mobile-app-automizer/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/automizer/mobile-app-automizer/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/automizer/mobile-app-automizer/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/automizer/mobile-app-automizer/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/automizer/mobile-app-automizer/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/automizer/mobile-app-automizer/merges",
                        "archive_url": "https://api.github.com/repos/automizer/mobile-app-automizer/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/automizer/mobile-app-automizer/downloads",
                        "issues_url": "https://api.github.com/repos/automizer/mobile-app-automizer/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/automizer/mobile-app-automizer/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/automizer/mobile-app-automizer/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/automizer/mobile-app-automizer/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/automizer/mobile-app-automizer/labels{/name}",
                        "releases_url": "https://api.github.com/repos/automizer/mobile-app-automizer/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/automizer/mobile-app-automizer/deployments",
                        "created_at": "2021-05-10T09:26:08Z",
                        "updated_at": "2021-05-16T12:34:33Z",
                        "pushed_at": "2021-05-15T16:18:52Z",
                        "git_url": "git://github.com/automizer/mobile-app-automizer.git",
                        "ssh_url": "git@github.com:automizer/mobile-app-automizer.git",
                        "clone_url": "https://github.com/automizer/mobile-app-automizer.git",
                        "svn_url": "https://github.com/automizer/mobile-app-automizer",
                        "homepage": null,
                        "size": 10836,
                        "stargazers_count": 501,
                        "watchers_count": 501,
                        "language": "JavaScript",
                        "has_issues": true,
                        "has_projects": true,
                        "has_downloads": true,
                        "has_wiki": true,
                        "has_pages": false,
                        "forks_count": 19,
                        "mirror_url": null,
                        "archived": false,
                        "disabled": false,
                        "open_issues_count": 0,
                        "license": {
                            "key": "mit",
                            "name": "MIT License",
                            "spdx_id": "MIT",
                            "url": "https://api.github.com/licenses/mit",
                            "node_id": "MDc6TGljZW5zZTEz"
                        },
                        "forks": 19,
                        "open_issues": 0,
                        "watchers": 501,
                        "default_branch": "master",
                        "score": 1
                    },
                ]
            },
            "status": 200,
            "statusText": "OK",
            "headers": {
                "cache-control": "no-cache",
                "content-length": "3569",
                "content-type": "application/json; charset=utf-8",
                "link": "<https://api.github.com/search/repositories?q=created%3A%3E2021-05-09&sort=stars&order=desc&per_page=5&page=2>; rel=\"next\", <https://api.github.com/search/repositories?q=created%3A%3E2021-05-09&sort=stars&order=desc&per_page=5&page=200>; rel=\"last\"",
                "x-github-media-type": "github.v3",
                "x-ratelimit-limit": "10",
                "x-ratelimit-remaining": "5",
                "x-ratelimit-reset": "1621173573",
                "x-ratelimit-resource": "search",
                "x-ratelimit-used": "5"
            },
            "config": {
                "url": "search/repositories?q=created:>2021-05-09&sort=stars&order=desc&per_page=5&page=1",
                "method": "get",
                "headers": {
                    "Accept": "application/json, text/plain, */*"
                },
                "baseURL": "https://api.github.com/",
                "transformRequest": [
                    null
                ],
                "transformResponse": [
                    null
                ],
                "timeout": 0,
                "xsrfCookieName": "XSRF-TOKEN",
                "xsrfHeaderName": "X-XSRF-TOKEN",
                "maxContentLength": -1,
                "maxBodyLength": -1
            },
            "request": {}
        };
    }
}